Repository ryantwt07/python-math-calculator-a-, pull requests merged in 2021-01, with the labels that each got.

#8 Spelling Errors
  README.md
Labels: Feature Request, Minor Update

#11 Created Coding Analysis
  .github/workflows/codeql-analysis.yml
Labels: Feature Request, Major Update

#12 More Functions
  version-2.py
Labels: Feature Request, Good First Issue, Major Update

#15 Publishing Errors
  code/version-2.py
Labels: Bug, Good First Issue, Minor Update

#16 Created For Version 3.0
  code/version-3.py
Labels: Major Update

#23 Added Instructions on How to Commit
  CONTRIBUTING.md
Labels: Feature Request, Good First Issue, Minor Update

#22 Added Different Variations of Pi
  code/version-3.py
Labels: Feature Request, Minor Update

#27 Addition of Matrix(Reviewed and changed)
  code/version-3.py
Labels: Custom Issues, Feature Request, Good First Issue, Minor Update

#29 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Feature Request, Major Update

#31 Added Basic Calculations
  code/version-3.py
Labels: Custom Issues, Feature Request, Major Update

#30 Updated for CLA
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Custom Issues, Feature Request, Minor Update

#32 Changed License Due to New User
  LICENSE
Labels: Custom Issues, Feature Request, Good First Issue, Minor Update

#34 Syntax Errors
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Custom Issues, Feature Request, Good First Issue, Minor Update

#35 Create File for Information of Supporting Versions
  supported.md
Labels: Custom Issues, Feature Request, Minor Update

#33 Publishing Errors
  code/version-3.py
Labels: Custom Issues, Feature Request, Good First Issue, Major Update

#39 Updated Issues Template due to CLA
  .github/ISSUE_TEMPLATE/custom-issues.md
  .github/ISSUE_TEMPLATE/for-bug-reports.md
  .github/ISSUE_TEMPLATE/for-feature-requests.md
  .github/ISSUE_TEMPLATE/for-systems-error.md
  .github/ISSUE_TEMPLATE/for-variable-error.md
Labels: Feature Request, Minor Update

#37 Created Version 4 Folder
  code/version-4.py
Labels: Feature Request, Good First Issue, Major Update
